spring:
  datasource:
    url: jdbc:mysql://49.50.167.118:3306/ljy?&allowMultiQueries=true
    username: root
    password: Dlwpdud123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver

  threads:
    virtual:
      enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
